### ISSUE TITLE
Proposal for a SIG for model signing and transparency

### ISSUE THREAD

**Issue by mihaimaruseac** [ossf/ai-ml-security#10]
**Purpose**: Create a cryptographic signing specification for artificial intelligence and machine learning models, addressing challenges such as very large models that can be used separately, and the signing of multiple disparate file formats held within a directory. This specification may have wider applicability to signing directories of multiple arbitrary file formats. This specification may later be proposed as a formal standard.

**Initial participants**:
- Laurent Simon (Google)
- Daniel Major (NVidia)
- Eoin Wickens (HiddenLayer)

**Comment by mihaimaruseac** [comment]
We have voted during the WG meeting and we got 15 "Yes" votes and 0 "No" votes

**Comment by TheFoxAtWork** [comment]
Is there a link to the deck presented at monday's meeting that could be added to this issue? How can individuals beyond the initial three identified become involved in this?

**Comment by mihaimaruseac** [comment]
I'll ask for the slides.

To get involved, I think we'll do post a calendar + zoom invite to this issue first and notify the working group and then the meetings will be happening periodically. I need to handle a few more processes for the launch of the SIG and then I'll notify here.

**Comment by laurentsimon** [comment]
The slides presented during the meeting are available [here](https://docs.google.com/presentation/d/1ncyxiNFOkAauR2GFEmo09qcOs9dFN3UD861rFAs6uMk/edit?usp=sharing)

Thanks again for the support and looking forward to making strides on the project!

**Comment by Ibrahim-Mukherjee** [comment]
Hi, I would be interested in writing documentation for this. Thanks.

**Comment by mihaimaruseac** [comment]
To update, the first meeting of the SIG will be on [May 15th at 8 AM Pacific time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240515T08&p1=137&ah=1) after which it will repeat every other week.

The event is now added to the OpenSSF calendar.

Hope to see everyone at the SIG meeting

**Comment by wenhuizhang** [comment]
+ 1 Wenhui Zhang (Bytedance)

**Comment by andife** [comment]
- 1 Andreas Fehlner (Onnx)

**Comment by mihaimaruseac** [comment]
The first meeting occurred today. The agenda is at https://docs.google.com/document/d/18oAsfhfKJurH-YTUFe520CAZS3lkORX1WnZmBv4Llkc/edit

**Comment by Ibrahim-Mukherjee** [comment]
Thanks reviewing now.

**Comment by mihaimaruseac** [comment]
Closing this one since the SIG (soon to be project, see ossf/tac#347) is formed and already had several meetings. There's nothing remaining to be done here
