### ISSUE TITLE
Document and propose taxonomy definitions

### ISSUE THREAD

**Issue by sevansdell** [ossf/ai-ml-security#15]
In our call today, @edelsohn shared https://genaicommons.org/glossary/ as a good resource for terminology. When I reviewed it later, I didn't see several security definitions listed, and would like to create the following definitions as a WG and propose them to the glossary:
-AIBOM
-model card
-manifest

These are terms were using in our call today, and I think adding the terms we've been thinking about (AIBOM and model manifest signing) may help the broader industry. 

Are there any other terms I'm missing?

**Comment by edelsohn** [comment]
- data card

**Comment by sevansdell** [comment]
A good idea, but going to put this on the "backburner" now and look at other priorities.
