### ISSUE TITLE
Update readme with more interlocks (e.g. CoSAI) and MVSR

### ISSUE THREAD

**Issue by sevansdell** [ossf/ai-ml-security#20]
@mihaimaruseac I think it would be helpful to include the meeting update interlocks on the read me with how we think we complement each other. This may be something we do over time, but at a minimum I think we should get the CoSAI stuff added (@camaleon2016). Maybe a topic to define in our next in person meeting, or we start a PR and collaborate on it asynch?

**Comment by mihaimaruseac** [comment]
This is a good idea, thank you. We can start with a PR now and update during the next meeting to make sure we didn't miss anything.

**Comment by sevansdell** [comment]
Additionally, we should update our MVSR, and the roadmap items we'd like to accomplish this year. One of the outcomes the Governing Board may seek during the November board meeting is publishing an updated MVSR. We may want AIML WG roadmap items to be upleveled to the OpenSSF MVSR.

**Comment by mihaimaruseac** [comment]
Closed by #24. I added a link to the spreadsheet that lists all interlocks and only summaries for a few of them
