### ISSUE TITLE
Please add content to the README of this repo

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/ai-ml-security#4]
Currently this repo README is very sparse. We need to add links & explanations. Please create PRs to do that!

**Comment by TheFoxAtWork** [comment]
From Today's (June 24th)
* Compile a list of where things occur and put it in a doc in the group repository
  * [Prior awareness of happenings in this space](https://docs.google.com/document/d/11tXIecCx-PHaLGJwqT_o31WbUVXHz7mR2auxArYwnjQ/edit)
  * Should also capture any group members that are participating in bodies outside of this group.
* Bring repository up to date, it’s been stale (also Jay, Emily)
  * [Review, refresh, and incorporate previous document on focus areas](https://docs.google.com/document/d/1jMIYg-VQUjdev2UL5yCcBXncpy6BtZa_zBjYEpxIjcs/edit)

**Comment by TheFoxAtWork** [comment]
This should be closed as completed and a new issue opened given the discussion on Mon Sep 30 2024 call
