### ISSUE TITLE
Voting for chair/co-chair

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/ai-ml-security#5]
Please (re-)vote for co-lead/chair of the AI/ML working group! We accidentally had two separate issues for voting, so we've decided to simply restart the vote. Please nominate someone (including yourself) and vote by adding +1 to the comment on that person. This is approval voting; vote for all the candidates you most approve of, and the 2 top vote recipients will become co-chairs. Appointment is for one year.

Voting deadline is October 11.

**Comment by david-a-wheeler** [comment]
Please +1 here for:

[Salkimmich](https://github.com/Salkimmich) (https://github.com/ossf/ai-ml-security/issues/3#issuecomment-1723430668)
I'll throw my hat for co-lead, and count me in on the WG no matter what!

One note: I'd recommend prioritize co-leads by specific regions/time zones to allow for global participation, this working group has pretty global engagement, and I'm happy to support meetings in different time zones as long as we all live on the same repo here.

**Comment by david-a-wheeler** [comment]
Please +1 here for
[therealnb](https://github.com/therealnb)(https://github.com/ossf/ai-ml-security/issues/2#issuecomment-1715272381)
Nigel Brown

I'd like to continue this work mostly because of all the fun and interesting people I meet and things I learn.

I offer a neutral agenda-free stance and hopefully a friendly face. You have all been to the meetings so I am a known quantity.

Quite obviously, my meeting skills leave a lot to be desired and I am no subject expert. I do not have a crystal clear vision of where this group should go, but I would like to enable it to find its way.

Please consider a vote for me!
(I will not be offended if you don't)

**Comment by camaleon2016** [comment]
Please +1 here for:

[camaleon2016] (https://github.com/camaleon2016) (https://github.com/ossf/ai-ml-security/issues/3#issuecomment-1723430668)
or
[camaleon2016] (https://github.com/camaleon2016) (https://github.com/ossf/ai-ml-security/issues/2#issuecomment-1715272381)

I'd like to be the conduit for getting work down and ensuring the efforts and initiatives of the all that have interest and enjoy work within AI, both engineers and program managers, are heard and implemented. 

I can help with community, and then neighborhood building within the OpenSSF and externally with other Open Source communities towards better understanding the current AI Landscape. This will help us to narrow our focus within OpenSSF's scope. 

I am a security guy through and through with an extremely high business acumen. Using these skills in my current role has allowed me autonomous movement across many internal and external orgs. I will continue to use these to expand our WGs reach.

Thank you for your consideration!
Please consider a vote here for Lead or Co-lead

**Comment by caabernathy** [comment]
Late entrant to the co-lead party.

Christine Abernathy, I lead the Open Source Program Office at F5 where I also focus on AI/ML. I'm very interested in efforts to collaborate across other entities - OpenSSF WGs, LF AI & Data, etc. It's a vast landscape and there are many synergies. I've attended most of the AI/ML meetings, represent them with the LF AI & Data ML Sec Committee, and I'm active in OpenSSF Best Practices and Identifying Security Threats WGs.

**Comment by toddysm** [comment]
+1 for @camaleon2016
Jay has been participating in several security efforts including WGs in OpenSSF and can help a lot with this one too.

**Comment by mihaimaruseac** [comment]
I think we can close this now that the voting ended
