### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by Frost-Lord** [ossf/ai-ml-security#6]
**Query:**
I have a question. I'm currently a year 12 student at school & I want to go into software engineering. I was wondering If I could join you guys in this project after my final exams are complete (HSC); As not only do I help the community but I can work with industry professionals.

**Questions:**
- What type of model will be used? (Bi-directional RNN, CNN etc.)
- What language will be used? (Python, Javascript, Typescript)
- Will TensorFlow be used?
- What specifically will we be making the Neural Network do?

If you have any questions, please don't hesitate to ask.

**Comment by david-a-wheeler** [comment]
Hi, we're not building a specific AI/ML model. We're trying to help others who build them, to improve their security.

**Comment by Frost-Lord** [comment]
Oh ok cool, I can help with that! Could I join as a trail contributor or do you want me to keep posting PR?

**Comment by Frost-Lord** [comment]
Also was the PR I made in the ball park of what your wanting for that section, just want to confirm before I write the content.
